spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?characterEncoding=utf8
    username: exercise
    password: 12345678
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8